/*File generated by custome templates
Important: Do not modify this file.Edit the file UserApplication.cs instead.
*/
#region using directives
using System;
using System.Transactions;
using System.ComponentModel;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using CleanArchitecture.US.Domain;
using CleanArchitecture.US.Common;
using CleanArchitecture.US.Common.Serilog;
using CleanArchitecture.US.Application.Interface;
using CleanArchitecture.US.Infrastructure.Interface;

#endregion

namespace CleanArchitecture.US.Application
{
     public class UserApplicationBase:BaseApplication, IBaseApplication<User>
    {
      #region Properties
         private IUserInfrastructure _userInfrastructure { get; }
      #endregion

      #region Constructor
       public UserApplicationBase(IUserInfrastructure userInfrastructure, IConfiguration configuration, ILoggerManager logger) : base(configuration, logger)
      {
        this._userInfrastructure = userInfrastructure;
      }
      #endregion

      #region Methods
       public async Task<User> Save(User entity, bool createTransaction) 
      {
        Logger.LogEnter();
        TransactionScope scope = null;
          try
         { 
         if (createTransaction)
         {
             scope = new TransactionScope(TransactionScopeOption.Required,
             TransactionScopeAsyncFlowOption.Enabled);
         }
          await Save(entity);
          scope?.Complete();
         } 
          finally 
         { 
          scope?.Dispose();
         Logger.LogExit();
         } 
          return entity; 
      }
      [DataObjectMethod(DataObjectMethodType.Update)]
       internal async Task<User> Save(User entity ) 
      {
        Logger.LogEnter();
           switch (entity.RowState) 
           { 
           case EntityState.New: 
            await _userInfrastructure.Insert(entity); 
           break; 
            case EntityState.Modified: 
            await _userInfrastructure.Update(entity); 
            break; 
           case EntityState.Deleted: 
           await _userInfrastructure.Delete(entity); 
            break; 
           } 
         Logger.LogExit();
          return entity; 
      }
       public async Task<IList<User>> Save(IList<User> entityCollection, bool createTransaction) 
      {
        Logger.LogEnter();
        TransactionScope scope = null;
          try
         { 
         if (createTransaction) 
         {
             scope = new TransactionScope(TransactionScopeOption.Required,
             TransactionScopeAsyncFlowOption.Enabled);
         }
          await Save(entityCollection);
          scope?.Complete();
         } 
          finally 
         { 
          scope?.Dispose();
         Logger.LogExit();
         } 
          return entityCollection; 
      }
      [DataObjectMethod(DataObjectMethodType.Update)]
       internal async Task<IList<User>>  Save( IList<User> entityCollection) 
      {
        Logger.LogEnter();
          try
         { 
          foreach (var entity in entityCollection) 
        {
           await _userInfrastructure.Update(entityCollection);  
         } 
         } 
          finally 
         { 
         Logger.LogExit();
         } 
          return entityCollection; 
      }
      [DataObjectMethod(DataObjectMethodType.Select)]
       public async Task<User> GetById(Int32  userId) 
      {
        Logger.LogEnter();
          try
         { 
         var entity = await _userInfrastructure.GetById(userId); 
         if(entity == null) return  new User();
           return entity; 
         } 
          finally 
         { 
         Logger.LogExit();
         } 
      }
      [DataObjectMethod(DataObjectMethodType.Select)]
       public async Task<IList<User>> GetListByForeignKeyAdminId(Int32 adminId) 
      {
        Logger.LogEnter();
          try
         { 
         return await _userInfrastructure.GetListByForeignKeyAdminId(adminId); 
         } 
          finally 
         { 
         Logger.LogExit();
         } 
      }
      [DataObjectMethod(DataObjectMethodType.Select)]
       public async Task<IList<User>> GetAll() 
      {
        Logger.LogEnter();
          try
         { 
         var collection = await _userInfrastructure.GetAll();
          return collection; 
         } 
          finally 
         { 
         Logger.LogExit();
         } 
      }
      #endregion
    }
    }

