/*
File generated by custome templates
Important: Do not modify this file. Edit the file EntityBase.cs instead.
*/

#region using directives

#endregion

namespace CleanArchitecture.US.Domain
{
    
    public class EntityBase
    {
        #region Constructors

        #endregion

        public EntityBase()
        {
            RowState = EntityState.New;
        }
        public EntityState RowState { get; set; }

        public void AcceptChanges()
        {
            RowState = EntityState.Unchanged;
        }

        public void RejectChanges()
        {
            RowState = EntityState.Unchanged;
        }

        public void EntityModified()
        {
            if (RowState == EntityState.Unchanged) RowState = EntityState.Modified;
        }

        public bool IsValid()
        {
            return true;
        }
    }

    public enum EntityState
    {
        Unchanged = 0,
        New = 1,
        Modified = 2,
        Deleted = 3,
        Excluded = 4
    }
}

