/*File generated by custome templates
Important: Do not modify this file.Edit the file AdminAccessApplication.cs instead.
*/
#region using directives
using System;
using System.Transactions;
using System.ComponentModel;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using CleanArchitecture.US.Domain;
using CleanArchitecture.US.Application.Interface;
using CleanArchitecture.US.Infrastructure.Interface;

#endregion

namespace CleanArchitecture.US.Application
{
     public class AdminAccessApplicationBase:BaseApplication, IBaseApplication<AdminAccess>
    {
      #region Properties
         private IAdminAccessInfrastructure _adminaccessInfrastructure { get; }
      #endregion

      #region Constructor
       public AdminAccessApplicationBase(IAdminAccessInfrastructure adminaccessInfrastructure, IConfiguration configuration, ILogger<AdminAccessApplication> logger) : base(configuration, logger)
      {
        this._adminaccessInfrastructure = adminaccessInfrastructure;
      }
      #endregion

      #region Methods
       public async Task<AdminAccess> Save(AdminAccess entity, bool createTransaction) 
      {
        //AppLogger.LogEnter();
        TransactionScope scope = null;
          try
         { 
         if (createTransaction)
         {
             scope = new TransactionScope(TransactionScopeOption.Required,
             new TransactionOptions { IsolationLevel = IsolationLevel.ReadUncommitted });
         }
          await Save(entity);
          scope?.Complete();
         } 
          finally 
         { 
          scope?.Dispose();
         //AppLogger.LogExit();
         } 
          return entity; 
      }
      [DataObjectMethod(DataObjectMethodType.Update)]
       internal async Task<AdminAccess> Save(AdminAccess entity ) 
      {
        //AppLogger.LogEnter();
        if (!entity.IsValid())
        {
          //throw new DataValidationException();
        }
           switch (entity.RowState) 
           { 
           case EntityState.New: 
            await _adminaccessInfrastructure.Insert(entity); 
           break; 
            case EntityState.Modified: 
            await _adminaccessInfrastructure.Update(entity); 
            break; 
           case EntityState.Deleted: 
           await _adminaccessInfrastructure.Delete(entity); 
            break; 
           } 
         //AppLogger.LogExit();
          return entity; 
      }
       public async Task<IList<AdminAccess>> Save(IList<AdminAccess> entityCollection, bool createTransaction) 
      {
        //AppLogger.LogEnter();
        TransactionScope scope = null;
          try
         { 
         if (createTransaction) 
         {
             scope = new TransactionScope(TransactionScopeOption.Required,
             new TransactionOptions { IsolationLevel = IsolationLevel.ReadUncommitted });
         }
          await Save(entityCollection);
          scope?.Complete();
         } 
          finally 
         { 
          scope?.Dispose();
         //AppLogger.LogExit();
         } 
          return entityCollection; 
      }
      [DataObjectMethod(DataObjectMethodType.Update)]
       internal async Task<IList<AdminAccess>>  Save( IList<AdminAccess> entityCollection) 
      {
        //AppLogger.LogEnter();
         bool isAllValid = true; 
          try
         { 
          foreach (var entity in entityCollection) 
        {
           if (!entity.IsValid()) isAllValid = false; 
        }
        if (!isAllValid)
        {
          //throw new DataValidationException();
        }
           await _adminaccessInfrastructure.Update(entityCollection);  
          return entityCollection; 
         } 
          finally 
         { 
         //AppLogger.LogExit();
         } 
      }
      [DataObjectMethod(DataObjectMethodType.Select)]
       public async Task<AdminAccess> GetById(Int32  adminAccessId) 
      {
        //AppLogger.LogEnter();
          try
         { 
         var entity = await _adminaccessInfrastructure.GetById(adminAccessId); 
         if(entity == null) return  new AdminAccess();
           return entity; 
         } 
          finally 
         { 
         //AppLogger.LogExit();
         } 
      }
      [DataObjectMethod(DataObjectMethodType.Select)]
       public async Task<IList<AdminAccess>> GetListByForeignKeyAdminId(Int32 adminId) 
      {
        //AppLogger.LogEnter();
          try
         { 
         return await _adminaccessInfrastructure.GetListByForeignKeyAdminId(adminId); 
         } 
          finally 
         { 
         //AppLogger.LogExit();
         } 
      }
      [DataObjectMethod(DataObjectMethodType.Select)]
       public async Task<IList<AdminAccess>> GetListByForeignKeyUserId(Int32 userId) 
      {
        //AppLogger.LogEnter();
          try
         { 
         return await _adminaccessInfrastructure.GetListByForeignKeyUserId(userId); 
         } 
          finally 
         { 
         //AppLogger.LogExit();
         } 
      }
      [DataObjectMethod(DataObjectMethodType.Select)]
       public async Task<IList<AdminAccess>> GetAll() 
      {
        //AppLogger.LogEnter();
          try
         { 
         var collection = await _adminaccessInfrastructure.GetAll();
          return collection; 
         } 
          finally 
         { 
         //AppLogger.LogExit();
         } 
      }
      #endregion
    }
    }

