/*File generated by custome templates
Important: Do not modify this file.Edit the file AdminApplication.cs instead.
*/
#region using directives
using System;
using System.Transactions;
using System.ComponentModel;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using CleanArchitecture.US.Domain;
using CleanArchitecture.US.Common;
using CleanArchitecture.US.Common.Serilog;
using CleanArchitecture.US.Application.Interface;
using CleanArchitecture.US.Infrastructure.Interface;

#endregion

namespace CleanArchitecture.US.Application
{
     public class AdminApplicationBase:BaseApplication, IBaseApplication<Admin>
    {
      #region Properties
         private IAdminInfrastructure _adminInfrastructure { get; }
      #endregion

      #region Constructor
       public AdminApplicationBase(IAdminInfrastructure adminInfrastructure, IConfiguration configuration, ILoggerManager logger) : base(configuration, logger)
      {
        this._adminInfrastructure = adminInfrastructure;
      }
      #endregion

      #region Methods
       public async Task<Admin> Save(Admin entity, bool createTransaction) 
      {
        Logger.LogEnter();
        TransactionScope scope = null;
          try
         { 
         if (createTransaction)
         {
             scope = new TransactionScope(TransactionScopeOption.Required,
             TransactionScopeAsyncFlowOption.Enabled);
         }
          await Save(entity);
          scope?.Complete();
         } 
          finally 
         { 
          scope?.Dispose();
         Logger.LogExit();
         } 
          return entity; 
      }
      [DataObjectMethod(DataObjectMethodType.Update)]
       internal async Task<Admin> Save(Admin entity ) 
      {
        Logger.LogEnter();
           switch (entity.RowState) 
           { 
           case EntityState.New: 
            await _adminInfrastructure.Insert(entity); 
           break; 
            case EntityState.Modified: 
            await _adminInfrastructure.Update(entity); 
            break; 
           case EntityState.Deleted: 
           await _adminInfrastructure.Delete(entity); 
            break; 
           } 
         Logger.LogExit();
          return entity; 
      }
       public async Task<IList<Admin>> Save(IList<Admin> entityCollection, bool createTransaction) 
      {
        Logger.LogEnter();
        TransactionScope scope = null;
          try
         { 
         if (createTransaction) 
         {
             scope = new TransactionScope(TransactionScopeOption.Required,
             TransactionScopeAsyncFlowOption.Enabled);
         }
          await Save(entityCollection);
          scope?.Complete();
         } 
          finally 
         { 
          scope?.Dispose();
         Logger.LogExit();
         } 
          return entityCollection; 
      }
      [DataObjectMethod(DataObjectMethodType.Update)]
       internal async Task<IList<Admin>>  Save( IList<Admin> entityCollection) 
      {
        Logger.LogEnter();
          try
         { 
          foreach (var entity in entityCollection) 
        {
           await _adminInfrastructure.Update(entityCollection);  
         } 
         } 
          finally 
         { 
         Logger.LogExit();
         } 
          return entityCollection; 
      }
      [DataObjectMethod(DataObjectMethodType.Select)]
       public async Task<Admin> GetById(Int32  adminId) 
      {
        Logger.LogEnter();
          try
         { 
         var entity = await _adminInfrastructure.GetById(adminId); 
         if(entity == null) return  new Admin();
           return entity; 
         } 
          finally 
         { 
         Logger.LogExit();
         } 
      }
      [DataObjectMethod(DataObjectMethodType.Select)]
       public async Task<IList<Admin>> GetAll() 
      {
        Logger.LogEnter();
          try
         { 
         var collection = await _adminInfrastructure.GetAll();
          return collection; 
         } 
          finally 
         { 
         Logger.LogExit();
         } 
      }
      #endregion
    }
    }

